In [1]:
import pandas as pd
import numpy as np
import requests as rq
import json as js
import datetime as dt

In [2]:
vehicles_df = pd.read_csv('Resources/vehicles.csv', low_memory=False)
vehicles_df.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,14.167143,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,27.046364,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,11.018889,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,27.046364,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,15.658421,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [3]:
vehicles_df.columns.values

array(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF',
       'co2', 'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08',
       'comb08U', 'combA08', 'combA08U', 'combE', 'combinedCD',
       'combinedUF', 'cylinders', 'displ', 'drive', 'engId', 'eng_dscr',
       'feScore', 'fuelCost08', 'fuelCostA08', 'fuelType', 'fuelType1',
       'ghgScore', 'ghgScoreA', 'highway08', 'highway08U', 'highwayA08',
       'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'hlv', 'hpv',
       'id', 'lv2', 'lv4', 'make', 'model', 'mpgData', 'phevBlended',
       'pv2', 'pv4', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy',
       'rangeHwyA', 'trany', 'UCity', 'UCityA', 'UHighway', 'UHighwayA',
       'VClass', 'year', 'youSaveSpend', 'baseModel', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2',
       'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'charge240b',
       'c240bDscr', 'createdOn', 'modifiedOn', 'startStop', 'phevCity',
       'phevHwy', 'phevComb'], dtype=object)

In [4]:
veh_reduced = vehicles_df[['year','VClass','comb08','cylinders','displ','drive','fuelType','trany']]
veh_reduced

,year,VClass,comb08,cylinders,displ,drive,fuelType,trany
0,1985,Two Seaters,21,4.0,2.0,Rear-Wheel Drive,Regular,Manual 5-spd
1,1985,Two Seaters,11,12.0,4.9,Rear-Wheel Drive,Regular,Manual 5-spd
2,1985,Subcompact Cars,27,4.0,2.2,Front-Wheel Drive,Regular,Manual 5-spd
3,1985,Vans,11,8.0,5.2,Rear-Wheel Drive,Regular,Automatic 3-spd
4,1993,Compact Cars,19,4.0,2.2,4-Wheel or All-Wheel Drive,Premium,Manual 5-spd
...,...,...,...,...,...,...,...,...
46559,1993,Compact Cars,22,4.0,2.2,Front-Wheel Drive,Regular,Automatic 4-spd
46560,1993,Compact Cars,23,4.0,2.2,Front-Wheel Drive,Regular,Manual 5-spd
46561,1993,Compact Cars,21,4.0,2.2,4-Wheel or All-Wheel Drive,Regular,Automatic 4-spd
46562,1993,Compact Cars,21,4.0,2.2,4-Wheel or All-Wheel Drive,Regular,Manual 5-spd
46563,1993,Compact Cars,18,4.0,2.2,4-Wheel or All-Wheel Drive,Premium,Automatic 4-spd

In [5]:
# veh_reduced['startStop'] = veh_reduced['startStop'].fillna('N')
# veh_reduced.head()

In [6]:
veh_reduced.dropna(how = 'any', inplace = True)
veh_reduced

C:\Users\kmill\AppData\Local\Temp\ipykernel_25304\4184643121.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veh_reduced.dropna(how = 'any', inplace = True)

,year,VClass,comb08,cylinders,displ,drive,fuelType,trany
0,1985,Two Seaters,21,4.0,2.0,Rear-Wheel Drive,Regular,Manual 5-spd
1,1985,Two Seaters,11,12.0,4.9,Rear-Wheel Drive,Regular,Manual 5-spd
2,1985,Subcompact Cars,27,4.0,2.2,Front-Wheel Drive,Regular,Manual 5-spd
3,1985,Vans,11,8.0,5.2,Rear-Wheel Drive,Regular,Automatic 3-spd
4,1993,Compact Cars,19,4.0,2.2,4-Wheel or All-Wheel Drive,Premium,Manual 5-spd
...,...,...,...,...,...,...,...,...
46559,1993,Compact Cars,22,4.0,2.2,Front-Wheel Drive,Regular,Automatic 4-spd
46560,1993,Compact Cars,23,4.0,2.2,Front-Wheel Drive,Regular,Manual 5-spd
46561,1993,Compact Cars,21,4.0,2.2,4-Wheel or All-Wheel Drive,Regular,Automatic 4-spd
46562,1993,Compact Cars,21,4.0,2.2,4-Wheel or All-Wheel Drive,Regular,Manual 5-spd
46563,1993,Compact Cars,18,4.0,2.2,4-Wheel or All-Wheel Drive,Premium,Automatic 4-spd

In [7]:
veh_reduced.dtypes

year           int64
VClass        object
comb08         int64
cylinders    float64
displ        float64
drive         object
fuelType      object
trany         object
dtype: object

In [8]:
sorted = veh_reduced.sort_values(by='year', axis=0, ascending=True)
sorted

,year,VClass,comb08,cylinders,displ,drive,fuelType,trany
20110,1984,Small Pickup Trucks 2WD,20,4.0,2.6,2-Wheel Drive,Regular,Manual 5-spd
19158,1984,Standard Pickup Trucks 4WD,18,6.0,2.8,4-Wheel or All-Wheel Drive,Regular,Automatic 4-spd
20319,1984,Special Purpose Vehicle 4WD,17,6.0,4.2,4-Wheel or All-Wheel Drive,Regular,Manual 4-spd
19156,1984,Standard Pickup Trucks 4WD,20,4.0,2.0,4-Wheel or All-Wheel Drive,Regular,Manual 5-spd
20320,1984,Special Purpose Vehicle 4WD,18,6.0,4.2,4-Wheel or All-Wheel Drive,Regular,Manual 5-spd
...,...,...,...,...,...,...,...,...
40243,2024,Subcompact Cars,21,6.0,3.0,All-Wheel Drive,Premium,Automatic 8-spd
40242,2024,Standard Sport Utility Vehicle 4WD,20,6.0,3.0,All-Wheel Drive,Premium,Automatic 9-spd
40241,2024,Standard Sport Utility Vehicle 4WD,20,6.0,3.0,All-Wheel Drive,Premium,Automatic 9-spd
40269,2024,Subcompact Cars,23,5.0,2.5,All-Wheel Drive,Premium,Automatic (AM-S7)
40267,2024,Two Seaters,27,4.0,2.0,Rear-Wheel Drive,Premium,Automatic (S8)

In [9]:
sorted.to_csv("Resources/vehicles_basic_clean.csv",index=False)

In [10]:
# counts of each makes' appearance in table

# make_counts = veh_reduced.make.value_counts()
# make_counts.head(5)

In [11]:
# make_counts_df = make_counts.to_frame()
# make_counts_df = make_counts_df[make_counts_df["make"]>10]
# make_counts_df

In [12]:
# # list of makes to keep
# make_list = make_counts_df.index.tolist()

# # remove small makes
# sorted_reduced = sorted[sorted.make.isin(make_list)]
# sorted_reduced

In [13]:


VClass_counts = sorted.VClass.value_counts()
VClass_counts.sort_index()

Compact Cars                          6039
Large Cars                            2433
Midsize Cars                          5247
Midsize Station Wagons                 490
Midsize-Large Station Wagons           640
Minicompact Cars                      1522
Minivan - 2WD                          387
Minivan - 4WD                           57
Small Pickup Trucks                    538
Small Pickup Trucks 2WD                500
Small Pickup Trucks 4WD                300
Small Sport Utility Vehicle 2WD        916
Small Sport Utility Vehicle 4WD       1606
Small Station Wagons                  1579
Special Purpose Vehicle                  1
Special Purpose Vehicle 2WD            736
Special Purpose Vehicle 4WD            344
Special Purpose Vehicles              1453
Special Purpose Vehicles/2wd             2
Special Purpose Vehicles/4wd             2
Sport Utility Vehicle - 2WD           1619
Sport Utility Vehicle - 4WD           2078
Standard Pickup Trucks                2354
Standard Pickup Trucks 2WD            1416
Standard Pickup Trucks 4WD            1400
Standard Pickup Trucks/2wd               4
Standard Sport Utility Vehicle 2WD     445
Standard Sport Utility Vehicle 4WD    1240
Subcompact Cars                       5219
Two Seaters                           2310
Vans                                  1141
Vans Passenger                           2
Vans, Cargo Type                       438
Vans, Passenger Type                   323
Name: VClass, dtype: int64

In [14]:
# function to automate reductions

def clean_up(df, column, replace):
    
    for c in replace:
        df.loc[vr[column].str.contains(c), column] = c

In [15]:
# reduce VClasses

vr = sorted.copy()
class_search_values = ["Minivan", "Small Pickup Trucks", "Special Purpose Vehicle", "Sport Utility Vehicle",\
                      "Standard Pickup Trucks","Vans", "Small Sport Utility Vehicle", "Standard Sport Utility Vehicle"]

# for c in class_search_values:
#     vr.loc[vr["VClass"].str.contains(c), "VClass"] = c
clean_up(vr, "VClass", class_search_values)    
    
vr.loc[vr["VClass"].str.contains("Midsize Station"), "VClass"] = "Midsize-Large Station Wagons"
    
vr["VClass"].value_counts()

Sport Utility Vehicle           7904
Compact Cars                    6039
Midsize Cars                    5247
Subcompact Cars                 5219
Standard Pickup Trucks          5174
Special Purpose Vehicle         2538
Large Cars                      2433
Two Seaters                     2310
Vans                            1904
Small Station Wagons            1579
Minicompact Cars                1522
Small Pickup Trucks             1338
Midsize-Large Station Wagons    1130
Minivan                          444
Name: VClass, dtype: int64

In [16]:
# reduce to 4, front or rear drive

vr.loc[vr["drive"].str.contains("2-Wheel"), "drive"] = "Front-Wheel Drive"
vr.loc[vr["drive"].str.contains("All-Wheel"), "drive"] = "4-Wheel Drive"
vr.loc[vr["drive"].str.contains("Part-time"), "drive"] = "4-Wheel Drive"
drive_counts = vr.drive.value_counts()
drive_counts.sort_index()

4-Wheel Drive        14075
Front-Wheel Drive    15692
Rear-Wheel Drive     15014
Name: drive, dtype: int64

In [17]:
# reduce to automatic or manual

AorM = ["Automatic", "Manual"]

clean_up(vr, "trany", AorM )

trany_counts = vr.trany.value_counts()
trany_counts.sort_index()

Automatic    32101
Manual       12680
Name: trany, dtype: int64

In [18]:
fuel_count = vr.fuelType.value_counts()
fuel_count

Regular                        27533
Premium                        14074
Gasoline or E85                 1393
Diesel                          1107
Midgrade                         159
Premium and Electricity          157
Premium or E85                   127
Regular Gas and Electricity       84
CNG                               60
Premium Gas or Electricity        55
Gasoline or natural gas           20
Gasoline or propane                8
Regular Gas or Electricity         4
Name: fuelType, dtype: int64

In [19]:
# remove non-gasoline fuels

vr = vr[(vr.fuelType == "Regular") | (vr.fuelType == "Premium")]
vr

,year,VClass,comb08,cylinders,displ,drive,fuelType,trany
20110,1984,Small Pickup Trucks,20,4.0,2.6,Front-Wheel Drive,Regular,Manual
19158,1984,Standard Pickup Trucks,18,6.0,2.8,4-Wheel Drive,Regular,Automatic
20319,1984,Special Purpose Vehicle,17,6.0,4.2,4-Wheel Drive,Regular,Manual
19156,1984,Standard Pickup Trucks,20,4.0,2.0,4-Wheel Drive,Regular,Manual
20320,1984,Special Purpose Vehicle,18,6.0,4.2,4-Wheel Drive,Regular,Manual
...,...,...,...,...,...,...,...,...
40243,2024,Subcompact Cars,21,6.0,3.0,4-Wheel Drive,Premium,Automatic
40242,2024,Sport Utility Vehicle,20,6.0,3.0,4-Wheel Drive,Premium,Automatic
40241,2024,Sport Utility Vehicle,20,6.0,3.0,4-Wheel Drive,Premium,Automatic
40269,2024,Subcompact Cars,23,5.0,2.5,4-Wheel Drive,Premium,Automatic
40267,2024,Two Seaters,27,4.0,2.0,Rear-Wheel Drive,Premium,Automatic

In [20]:
vr = vr.drop("fuelType", axis=1)

In [21]:
vr = vr.rename(columns={"comb08": "MPG(comb)", "VClass": "vehicle_class","displ":"displ (L)"})
vr

,year,vehicle_class,MPG(comb),cylinders,displ (L),drive,trany
20110,1984,Small Pickup Trucks,20,4.0,2.6,Front-Wheel Drive,Manual
19158,1984,Standard Pickup Trucks,18,6.0,2.8,4-Wheel Drive,Automatic
20319,1984,Special Purpose Vehicle,17,6.0,4.2,4-Wheel Drive,Manual
19156,1984,Standard Pickup Trucks,20,4.0,2.0,4-Wheel Drive,Manual
20320,1984,Special Purpose Vehicle,18,6.0,4.2,4-Wheel Drive,Manual
...,...,...,...,...,...,...,...
40243,2024,Subcompact Cars,21,6.0,3.0,4-Wheel Drive,Automatic
40242,2024,Sport Utility Vehicle,20,6.0,3.0,4-Wheel Drive,Automatic
40241,2024,Sport Utility Vehicle,20,6.0,3.0,4-Wheel Drive,Automatic
40269,2024,Subcompact Cars,23,5.0,2.5,4-Wheel Drive,Automatic
40267,2024,Two Seaters,27,4.0,2.0,Rear-Wheel Drive,Automatic

In [22]:
vr.to_csv("Resources/vehicles_fully_reduced.csv",index=False)